### ISSUE TITLE
UndefinedTransactionType: <class 'sbds.storages.db.tables.tx.UndefinedTransactionType'>

### ISSUE THREAD

**Issue by john-g-g** [steemit/sbds#31] opened 2017-03-03 05:55 UTC
View details in Rollbar: [https://rollbar.com/Steemit/sbds/items/3/](https://rollbar.com/Steemit/sbds/items/3/)

```
Traceback (most recent call last):
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/scripts/populate.py", line 385, in block_adder_process_worker
    results = bulk_add(raw_blocks_chunk, session)
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/__init__.py", line 275, in bulk_add
    chain.from_iterable(map(TxBase.from_raw_block, raw_blocks_chunk)))
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/tables/tx.py", line 102, in from_raw_block
    prepared = [cls._prepare_for_storage(data_dict=d) for d in operations]
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/tables/tx.py", line 102, in <listcomp>
    prepared = [cls._prepare_for_storage(data_dict=d) for d in operations]
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/tables/tx.py", line 65, in _prepare_for_storage
    tx_cls = cls.tx_class_for_type(op_type)
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/tables/tx.py", line 125, in tx_class_for_type
    raise UndefinedTransactionType(tx_type)
UndefinedTransactionType: escrow_transfer
```

**Comment by sneak** [comment] 2017-03-04 06:49
dupe of #29

**Closed by sneak** 2017-03-04 06:49 UTC
